### ISSUE TITLE
Error in parsing file

### ISSUE THREAD

**Issue by ertanden** [wackou/guessit#184]
The command is:
```bash
$ guessit Stay\ \(2005\)\ \[1080p\]/Stay.2005.1080p.BluRay.x264.YIFY.mp4
```

The error is:
```python
Traceback (most recent call last):
  File "/usr/local/bin/guessit", line 9, in <module>
    load_entry_point('guessit==0.10.0', 'console_scripts', 'guessit')()
  File "/Library/Python/2.7/site-packages/guessit-0.10.0-py2.7.egg/guessit/__main__.py", line 278, in main
    options=vars(options))
  File "/Library/Python/2.7/site-packages/guessit-0.10.0-py2.7.egg/guessit/__main__.py", line 38, in guess_file
    guess = guess_file_info(filename, info, options, **kwargs)
  File "/Library/Python/2.7/site-packages/guessit-0.10.0-py2.7.egg/guessit/__init__.py", line 288, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "/Library/Python/2.7/site-packages/guessit-0.10.0-py2.7.egg/guessit/__init__.py", line 111, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "/Library/Python/2.7/site-packages/guessit-0.10.0-py2.7.egg/guessit/__init__.py", line 118, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=options, **kwargs)
  File "/Library/Python/2.7/site-packages/guessit-0.10.0-py2.7.egg/guessit/matcher.py", line 121, in __init__
    self._process(transformer, False)
  File "/Library/Python/2.7/site-packages/guessit-0.10.0-py2.7.egg/guessit/matcher.py", line 139, in _process
    transformer.process(self.match_tree, self.options)
  File "/Library/Python/2.7/site-packages/guessit-0.10.0-py2.7.egg/guessit/transfo/guess_movie_title_from_position.py", line 106, in process
    node = next(groups_before)
StopIteration
```

**Comment by Toilal** [comment]
Thanks for reporting this bug.
