### ISSUE TITLE
Traceback when trying to process an anime episode

### ISSUE THREAD

**Issue by nathan-hoad** [wackou/guessit#194]
```
$ guessit "[Figmentos] Monster 34 - At the End of Darkness [781219F1].mkv"
For: [Figmentos] Monster 34 - At the End of Darkness [781219F1].mkv
Traceback (most recent call last):
  File "/home/nathan/.local/bin//guessit", line 9, in <module>
    load_entry_point('guessit==0.10.3.dev0', 'console_scripts', 'guessit')()
  File "/home/nathan/projects/guessit/guessit/__main__.py", line 277, in main
    options=vars(options))
  File "/home/nathan/projects/guessit/guessit/__main__.py", line 38, in guess_file
    guess = guess_file_info(filename, info, options, **kwargs)
  File "/home/nathan/projects/guessit/guessit/__init__.py", line 291, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "/home/nathan/projects/guessit/guessit/__init__.py", line 111, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "/home/nathan/projects/guessit/guessit/__init__.py", line 118, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=options, **kwargs)
  File "/home/nathan/projects/guessit/guessit/matcher.py", line 120, in __init__
    self._process(transformer, False)
  File "/home/nathan/projects/guessit/guessit/matcher.py", line 138, in _process
    transformer.process(self.match_tree, self.options)
  File "/home/nathan/projects/guessit/guessit/transfo/guess_bonus_features.py", line 62, in process
    found_property(title, 'title', confidence=0.9)
  File "/home/nathan/projects/guessit/guessit/matcher.py", line 193, in found_property
    guess = build_guess(node, name, value, confidence)
  File "/home/nathan/projects/guessit/guessit/matcher.py", line 166, in build_guess
    guess = Guess({name: node.clean_value if value is None else value}, confidence=confidence)
AttributeError: 'NoneType' object has no attribute 'clean_value'
```
If I put in a tiny patch to handle the iterator running over, then it completes successfully, but with some issues:

```
diff --git a/guessit/transfo/guess_bonus_features.py b/guessit/transfo/guess_bonus_features.py
index c70b31e..f321306 100644
--- a/guessit/transfo/guess_bonus_features.py
+++ b/guessit/transfo/guess_bonus_features.py
@@ -58,7 +58,8 @@ class GuessBonusFeatures(Transformer):
             found_property(film_series, 'filmSeries', confidence=0.9)
 
             title = next_group(film_number[0])
-            found_property(title, 'title', confidence=0.9)
+            if title is not None:
+                found_property(title, 'title', confidence=0.9)
 
         season = [node for node in mtree.leaves() if 'season' in node.guess]
         if season and 'bonusNumber' in mtree.info:
```

Result after patch:
```
$ guessit "[Figmentos] Monster 34 - At the End of Darkness [781219F1].mkv"
For: [Figmentos] Monster 34 - At the End of Darkness [781219F1].mkv
GuessIt found: {
    [0.90] "filmSeries": "At the End of Darkness",
    [1.00] "type": "episode",
    [1.00] "mimetype": "video/x-matroska",
    [0.64] "releaseGroup": "Figmentos",
    [0.70] "series": "Monster",
    [1.00] "filmNumber": 1,
    [1.00] "date": "1978-12-19",
    [0.40] "episodeNumber": 34,
    [1.00] "container": "mkv"
}
```

So the `filmSeries` should actually be `title`, indicating this was picked up as a movie to some degree I guess? Strange considering the `series` field certainly indicates it's a series. The date is also terribly incorrect, but given the checksum certainly looks like a date for the most part, I don't think that's too common a thing to have happen. The `filmNumber` is also wrong and picked up from the F1 part of the checksum.

**Comment by Toilal** [comment]
the crc32 property should be guessed before the filmNumber, because it's in a transformer with higher priority. For some reason, it is not guessed at all, and the F1 is guessed as `filmNumber` afterward.

The traceback is related to missing NoneType checks in bonus transformer.

**Comment by Toilal** [comment]
At is also catched as a country, i'll exclude it.

**Comment by Toilal** [comment]
Problem is that `781219` part of the CRC is guessed as a date ! `1978-12-19`. `crc32` should have higher priority than `date`.
