### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded in cmp

### ISSUE THREAD

**Issue by Diaoul** [wackou/guessit#212]
guessit "Star Trek Into Darkness (2013)/star.trek.into.darkness.2013.720p.web-dl.h264-publichd.mkv"

```
  File "/root/env/lib/python2.7/site-packages/guessit-0.10.3-py2.7.egg/guessit/matcher.py", line 307, in process_node
    self.process_node(node, partial_span=partition_span)
  File "/root/env/lib/python2.7/site-packages/guessit-0.10.3-py2.7.egg/guessit/matcher.py", line 307, in process_node
    self.process_node(node, partial_span=partition_span)
  File "/root/env/lib/python2.7/site-packages/guessit-0.10.3-py2.7.egg/guessit/matcher.py", line 307, in process_node
    self.process_node(node, partial_span=partition_span)
  File "/root/env/lib/python2.7/site-packages/guessit-0.10.3-py2.7.egg/guessit/matcher.py", line 307, in process_node
    self.process_node(node, partial_span=partition_span)
  File "/root/env/lib/python2.7/site-packages/guessit-0.10.3-py2.7.egg/guessit/matcher.py", line 247, in process_node
    matcher_result = self.guess_func(string, node, self.options)
  File "/root/env/lib/python2.7/site-packages/guessit-0.10.3-py2.7.egg/guessit/transfo/guess_language.py", line 45, in guess_language
    guess = search_language(string, allowed_languages)
  File "/root/env/lib/python2.7/site-packages/guessit-0.10.3-py2.7.egg/guessit/language.py", line 271, in search_language
    for prop, language, lang, word in find_possible_languages(string, allowed_languages):
  File "/root/env/lib/python2.7/site-packages/guessit-0.10.3-py2.7.egg/guessit/language.py", line 245, in find_possible_languages
    elif lang == 'mul' or hasattr(lang, 'alpha2'):
  File "build/bdist.linux-x86_64/egg/babelfish/language.py", line 159, in __eq__
  File "build/bdist.linux-x86_64/egg/babelfish/language.py", line 178, in __str__
  File "build/bdist.linux-x86_64/egg/babelfish/language.py", line 150, in __getattr__
  File "build/bdist.linux-x86_64/egg/babelfish/converters/__init__.py", line 236, in __getitem__
RuntimeError: maximum recursion depth exceeded in cmp
```

**Comment by hardware** [comment]
Same issue with Sickrage :+1: 

```
2015-07-26 13:56:49 INFO     FINDSUBTITLES :: Checking for subtitles
2015-07-26 13:56:55 INFO     POSTPROCESSER :: PostProcessing Path: /var/medias/complete-downloads
2015-07-26 13:57:02 INFO     POSTPROCESSER :: Processing completed
2015-07-26 13:57:14 INFO     FINDSUBTITLES :: Error occurred when downloading subtitles for: /var/medias/series/The Originals/Season 02/The.Originals.S02E15.720p.HDTV.X264-DIMENSION.mkv
2015-07-26 13:57:14 ERROR    FINDSUBTITLES :: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/tv.py", line 1469, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "/opt/sickrage/lib/subliminal/api.py", line 88, in download_best_subtitles
    for subtitle, score in sorted([(s, s.compute_score(video)) for s in video_subtitles],
  File "/opt/sickrage/lib/subliminal/subtitle.py", line 131, in compute_score
    initial_matches = self.compute_matches(video)
  File "/opt/sickrage/lib/subliminal/providers/opensubtitles.py", line 61, in compute_matches
    matches |= compute_guess_matches(video, guessit.guess_episode_info(self.movie_release_name + '.mkv'))
  File "/opt/sickrage/lib/guessit/__init__.py", line 358, in guess_episode_info
    return guess_file_info(filename, info=info, options=options, type='episode', **kwargs)
  File "/opt/sickrage/lib/guessit/__init__.py", line 290, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "/opt/sickrage/lib/guessit/__init__.py", line 110, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "/opt/sickrage/lib/guessit/__init__.py", line 123, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=merged_options, **kwargs)
  File "/opt/sickrage/lib/guessit/matcher.py", line 120, in __init__
    self._process(transformer, False)
  File "/opt/sickrage/lib/guessit/matcher.py", line 138, in _process
    transformer.process(self.match_tree, self.options)
  File "/opt/sickrage/lib/guessit/transfo/guess_language.py", line 141, in process
    GuessFinder(self.guess_language, None, self.log, options).process_nodes(mtree.unidentified_leaves())
  File "/opt/sickrage/lib/guessit/matcher.py", line 236, in process_nodes
    self.process_node(node)
  File "/opt/sickrage/lib/guessit/matcher.py", line 308, in process_node
    self.process_node(node, partial_span=partition_span)
  File "/opt/sickrage/lib/guessit/matcher.py", line 308, in process_node
    self.process_node(node, partial_span=partition_span)
  File "/opt/sickrage/lib/guessit/matcher.py", line 308, in process_node
    self.process_node(node, partial_span=partition_span)
   ...
   ...
   RuntimeError: maximum recursion depth exceeded
```

Related to this issue : https://github.com/SiCKRAGETV/sickrage-issues/issues/2339
