### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by didyouexpectthat** [wackou/guessit#225]
I use guessit through SickRage.
I am constantly getting errors in SickRage regarding:
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/usr/share/sickrage/sickbeard/tv.py", line 1469, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "/usr/share/sickrage/lib/subliminal/api.py", line 88, in download_best_subtitles
    for subtitle, score in sorted([(s, s.compute_score(video)) for s in video_subtitles],
  File "/usr/share/sickrage/lib/subliminal/subtitle.py", line 131, in compute_score
    initial_matches = self.compute_matches(video)
  File "/usr/share/sickrage/lib/subliminal/providers/opensubtitles.py", line 61, in compute_matches
    matches |= compute_guess_matches(video, guessit.guess_episode_info(self.movie_release_name + '.mkv'))
  File "/usr/share/sickrage/lib/guessit/__init__.py", line 370, in guess_episode_info
    return guess_file_info(filename, info=info, options=options, type='episode', **kwargs)
  File "/usr/share/sickrage/lib/guessit/__init__.py", line 302, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "/usr/share/sickrage/lib/guessit/__init__.py", line 114, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "/usr/share/sickrage/lib/guessit/__init__.py", line 121, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=options, **kwargs)
  File "/usr/share/sickrage/lib/guessit/matcher.py", line 120, in __init__
    self._process(transformer, False)
  File "/usr/share/sickrage/lib/guessit/matcher.py", line 138, in _process
    transformer.process(self.match_tree, self.options)
  File "/usr/share/sickrage/lib/guessit/transfo/guess_release_group.py", line 219, in process
    GuessFinder(self.guess_release_group, None, self.log, options).process_nodes(mtree.unidentified_leaves())
  File "/usr/share/sickrage/lib/guessit/matcher.py", line 227, in process_nodes
    self.process_node(node)
  File "/usr/share/sickrage/lib/guessit/matcher.py", line 236, in process_node
    matcher_result = self.guess_func(string, node, self.options)
  File "/usr/share/sickrage/lib/guessit/transfo/guess_release_group.py", line 165, in guess_release_group
    guess = self.container.as_guess(found, string, self.validate_group_name)
  File "/usr/share/sickrage/lib/guessit/containers.py", line 639, in as_guess
    if filter_(guess):
  File "/usr/share/sickrage/lib/guessit/transfo/guess_release_group.py", line 96, in validate_group_name
    if self.re_sep.match(val[0]):
IndexError: string index out of range
```
```
2015-08-28 10:16:59 ERROR FINDSUBTITLES :: Traceback (most recent call last):
2015-08-28 10:16:59 INFO FINDSUBTITLES :: Error occurred when downloading subtitles for: /tv/The Mindy Project/s02e07.mkv
2015-08-28 10:16:57 ERROR FINDSUBTITLES :: Traceback (most recent call last):
2015-08-28 10:16:57 INFO FINDSUBTITLES :: Error occurred when downloading subtitles for: /tv/The Mindy Project/s02e06.mkv
2015-08-28 10:16:55 ERROR FINDSUBTITLES :: Traceback (most recent call last):
2015-08-28 10:16:55 INFO FINDSUBTITLES :: Error occurred when downloading subtitles for: /tv/The Mindy Project/s02e05.mkv
2015-08-28 10:16:52 ERROR FINDSUBTITLES :: Traceback (most recent call last):
2015-08-28 10:16:52 INFO FINDSUBTITLES :: Error occurred when downloading subtitles for: /tv/The Mindy Project/s02e04.mkv
2015-08-28 10:16:50 ERROR FINDSUBTITLES :: Traceback (most recent call last):
2015-08-28 10:16:50 INFO FINDSUBTITLES :: Error occurred when downloading subtitles for: /tv/The Mindy Project/s02e03.mkv
2015-08-28 10:16:46 ERROR FINDSUBTITLES :: Traceback (most recent call last):
2015-08-28 10:16:46 INFO FINDSUBTITLES :: Error occurred when downloading subtitles for: /tv/The Mindy Project/s02e02.mkv
2015-08-28 10:16:44 ERROR FINDSUBTITLES :: Traceback (most recent call last):
2015-08-28 10:16:44 INFO FINDSUBTITLES :: Error occurred when downloading subtitles for: /tv/The Mindy Project/s02e01.mkv
```
```
SR Version:	BRANCH: (develop) / COMMIT: (a7193c6983e62205360aac40d937ce9e846b6852) 
SR User:	sickrage
SR Locale:	(None, None)
SR Config file:	/usr/share/sickrage/config.ini
SR Database file:	/usr/share/sickrage/sickbeard.db
SR Cache Dir:	/usr/share/sickrage/cache
SR Log Dir:	/usr/share/sickrage/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch', '--datadir=/usr/share/sickrage']
Python Version:	2.7.9 (default, Mar 1 2015, 12:57:24) [GCC 4.9.2]
```

**Comment by didyouexpectthat** [comment]
It continuously is erroring out on these files, but not other files. All my files appear the exact same /tv/[Show]/s##e##.<ext>

**Comment by didyouexpectthat** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2176
I did open an issue with SickRage but miigotu is insisting that this is an issue with guessit.

**Comment by Toilal** [comment]
I can't reproduce, sorry : 

```
For: /tv/show/s01e02.mkv
GuessIt found: {
    [1.00] "season": 1,
    [1.00] "mimetype": "video/x-matroska",
    [1.00] "type": "episode",
    [1.00] "episodeNumber": 2,
    [1.00] "container": "mkv",
    [0.30] "series": "show"
}
```

**Comment by Toilal** [comment]
I can't reproduce, sorry

```
For: /tv/show/s01e02.mkv
GuessIt found: {
    [1.00] "season": 1,
    [1.00] "mimetype": "video/x-matroska",
    [1.00] "type": "episode",
    [1.00] "episodeNumber": 2,
    [1.00] "container": "mkv",
    [0.30] "series": "show"
}
```

**Comment by Toilal** [comment]
Even if I can't reproduce it, there's something unsafe in the code that can cause this exact traceback, so I'll fix it.
