### ISSUE TITLE
Latest version (0.10.x) does not install with easy_install3

### ISSUE THREAD

**Issue by crazyquark** [wackou/guessit#228]
Only version 0.9.0 works for me.

```
Attempting to install anything from 0.10.0 and above I get:
Downloading https://pypi.python.org/packages/source/g/guessit/guessit-0.10.0.zip#md5=0cad81d760544510ec74978afc84b6ec
Processing guessit-0.10.0.zip
Writing /tmp/easy_install-bm_xfs3f/guessit-0.10.0/setup.cfg
Running guessit-0.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-bm_xfs3f/guessit-0.10.0/egg-dist-tmp-6ptz3tq3
Traceback (most recent call last):
  File "/usr/bin/easy_install3", line 9, in <module>
    load_entry_point('setuptools==5.5.1', 'console_scripts', 'easy_install')()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 2199, in main
    lambda: setup(
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 2185, in with_ei_usage
    return f()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 2202, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 393, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 636, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 666, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 856, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1078, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1063, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 68, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 114, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 67, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-bm_xfs3f/guessit-0.10.0/setup.py", line 28, in <module>
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 788: ordinal not in range(128)
```

**Comment by crazyquark** [comment]
Looks like an encoding issue.
However:
Python 3.4.2 (default, Oct  8 2014, 14:38:51) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'

**Comment by Toilal** [comment]
We have discussed those king of problems in this issue : https://github.com/wackou/guessit/issues/209 read the latest answers about encoding.

What gives `sys.stdout.encoding` ? and what gives `$ locale` from shell ?

**Comment by crazyquark** [comment]
I see
>>> sys.stdout.encoding
'UTF-8'

...
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=ro_RO.UTF-8
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=ro_RO.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=ro_RO.UTF-8
LC_NAME=ro_RO.UTF-8
LC_ADDRESS=ro_RO.UTF-8
LC_TELEPHONE=ro_RO.UTF-8
LC_MEASUREMENT=ro_RO.UTF-8
LC_IDENTIFICATION=ro_RO.UTF-8
LC_ALL=

**Comment by Toilal** [comment]
can you try to install the last release ? `0.10.4`

**Comment by crazyquark** [comment]
Yes, I have the same problem on 0.10.4.

**Comment by Toilal** [comment]
@crazyquark Any advances or idea about this issue ?
